### ISSUE TITLE
testing with cli?

### ISSUE THREAD

**Issue by haldiggs** [BryanHunt/ember-d3-components#1]
hey Bryan I wondered if you still considered this project viable. The cli version hasn't been updated in quite a while. Is this supposed to be working?

**Comment by BryanHunt** [comment]
I haven't done much with this project, but would like to get back to it.  MongoDB 3.x has consumed all of my open source time lately.  If you have any interest in collaborating, PR's are very welcome.

**Comment by haldiggs** [comment]
ok thanks for the answer. if I get a chance I'll think about it. Tried up in a release cycle for a while.

**Comment by BryanHunt** [comment]
FYI, I have pushed an update to master with the latest ember-cli.

**Comment by haldiggs** [comment]
sweet, thanks so much.
